## CHANGE this to the name of your plugin.
name: SlimeCustomizer

## CHANGE this to your username.
author: NCBPFluffyBear

## CHANGE this to a meaninful but short description of your plugin.
description: A Slimefun4 addon that allows the creation of items through simple configuration files

## CHANGE this to the path of the class that extends JavaPlugin.
main: io.ncbpfluffybear.slimecustomizer.SlimeCustomizer

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/NCBPFluffyBear/SlimeCustomizer

## This is required and marks Slimefun as a plugin dependency.
depend: [Slimefun]
softdepend:
  - ChestTerminal
  - ColoredEnderChests
  - DyedBackpacks
  - EcoPower
  - ElectricSpawners
  - ExoticGarden
  - ExtraGear
  - ExtraHeads
  - HotbarPets
  - luckyblocks-sf
  - PrivateStorage
  - SlimefunOreChunks
  - SlimyTreeTaps
  - SoulJars
  - CommandOverride
  - CS-CoreLib
  - EmeraldEnchants2
  - QuickMarket
  - QuickSell
  - RankPrefixPlus
  - LiteXpansion
  - MobCapturer
  - SoundMuffler
  - ExtraTools
  - TranscEndence
  - Liquid
  - SFCalc
  - SlimefunWarfare
  - Slimy-Power-Suits
  - FluffyMachines
  - SlimyRepair
  - InfinityExpansion
  - FoxyMachines
  - GlobalWarming
  - DynaTech
  - GeneticChickengineering
  - HeadLimiter
  - SlimeXpansion
  - Barrels
  - ClayTech
  - FNAmplifications
  - SMG
  - EMC2
  - Simple-Storage
  - AlchimiaVitae
  - SlimeTinker
  - PotionExpansion
  - FlowerPower
  - Galactifun
  - Element-Manipulation
  - CrystamaeHistoria
  - DankTech2
  - Networks
  - VillagerUtil
  - MissileWarfare
  - SensibleToolbox
  - RelicsOfCthonia
  - Supreme

  ## This value is automatically replaced by the version specified in your pom.xml file, do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.16

commands:
  slimecustomizer:
    description: SlimeCustomizer Command
    usage: /<command>
    aliases: [sc]

permissions:
  slimecustomizer.admin:
    description: Give access to SlimeCustomizer admin commands
    default: op
